### ISSUE TITLE
Tensor size not matchable

### ISSUE THREAD

**Issue by tchaton** [Oldpan/Deep-Painterly-Harmonization-Pytorch#5]
python train.py give me

True
===> Using GPU to train
===> Loaing datasets
the image ndarray size is (682, 700, 3)
===> Initialize the image...
the image tensor size is torch.Size([1, 3, 682, 700])
===> Building the painterly model...
-----Setting up style layer-----
-----Setting up style layer-----
-----Setting up content layer-----
-----Setting up style layer-----
-----Setting up style layer-----
-----Setting up style layer-----
===> Optimizer running...
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    content_image, mask_image, tmask_image)
  File "train.py", line 200, in run_painterly_transfer
    optimizer.step(closure)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/optim/lbfgs.py", line 103, in step
    orig_loss = closure()
  File "train.py", line 178, in closure
    loss.backward()
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/tchaton/projects/original/Deep-Painterly-Harmonization-Pytorch/model.py", line 118, in style_hook
    'grad_input:{} is not matchable with mask:{}'.format(grad_input[0].shape, self.mask.shape)
AssertionError: grad_input:torch.Size([1, 128, 170, 175]) is not matchable with mask:torch.Size([1, 1, 170, 175])

**Comment by yxwang-10** [comment]
Hello, I have the same question. Have you finished this problem?

**Comment by Dttong** [comment]
Hello, I have the same question. Have you finished this problem?
